name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry.harbor.replicas.io
        uses: docker/login-action@v1
        with:
          registry: registry.harbor.replicas.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.harbor.replicas.io/library/toolbox:latest
          build-args: |
            USER_ID=501
            USER_NAME=siw36
            ANSIBLE_VERSION="2.11.2"
            

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
